### ISSUE TITLE
Eliom/Toolkit: Client-side programming

### ISSUE THREAD

**Issue by balat** [ocsigen/ocamlweb-roadmap#10]
```[tasklist]
### Tasks
- [ ] Write tests for Eliom used without server
- [ ] Test client-only services
- [ ] Write tests for Toolkit client only
- [ ] Write tutorial
```
