### ISSUE TITLE
Eliom with wasm

### ISSUE THREAD

**Issue by balat** [ocsigen/ocamlweb-roadmap#5]
```[tasklist]
### Tasks
- [ ] Build system for building both wasm and js version
- [ ] Send one or the other depending on user-agent
- [ ] Configure to use wasm or not
```
